package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudProfessionFile;

import java.util.List;

public interface CloudProfessionFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    int insert(CloudProfessionFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    int insertSelective(CloudProfessionFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    CloudProfessionFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudProfessionFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_profession_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudProfessionFile record);

    int insertBatch(List<CloudProfessionFile> cloudProfessionFiles);
}