package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudParkingSpace;

import java.util.List;

public interface CloudParkingSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    int insert(CloudParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    int insertSelective(CloudParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    CloudParkingSpace selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_parking_space
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudParkingSpace record);

    List<CloudParkingSpace> selectByObj(CloudParkingSpace param);

    int insertBatch(List<CloudParkingSpace> models);
}