package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudHouseType;

import java.util.List;

public interface CloudHouseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    int insert(CloudHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    int insertSelective(CloudHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    CloudHouseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_house_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudHouseType record);

    int insertBatch(List<CloudHouseType> cloudHouseTypes);
}