package com.yuezhu.crawler.dao;


import com.yuezhu.crawler.model.CloudDataOffice;

import java.util.List;

public interface CloudDataOfficeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    int insert(CloudDataOffice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    int insertSelective(CloudDataOffice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    CloudDataOffice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudDataOffice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_data_office
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudDataOffice record);

    List<CloudDataOffice> selectByObj(CloudDataOffice param);

    int insertBatch(List<CloudDataOffice> cloudDataOfficeList);
}