package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudRentHouse;

import java.util.List;

public interface CloudRentHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    int insert(CloudRentHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    int insertSelective(CloudRentHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    CloudRentHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudRentHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_rent_house
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudRentHouse record);

    List<CloudRentHouse> selectByObj(CloudRentHouse param);

    int insertBatch(List<CloudRentHouse> models);
}