package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudNewPremises;

import java.util.List;

public interface CloudNewPremisesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    int insert(CloudNewPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    int insertSelective(CloudNewPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    CloudNewPremises selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudNewPremises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_new_premises
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudNewPremises record);

    List<CloudNewPremises> selectByObj(CloudNewPremises param);

    int insertBatch(List<CloudNewPremises> models);
}