package com.yuezhu.crawler.dao;

import com.yuezhu.crawler.model.CloudPioneerPark;

import java.util.List;

public interface CloudPioneerParkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    int insert(CloudPioneerPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    int insertSelective(CloudPioneerPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    CloudPioneerPark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CloudPioneerPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_pioneer_park
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CloudPioneerPark record);

    List<CloudPioneerPark> selectByObj(CloudPioneerPark param);

    int insertBatch(List<CloudPioneerPark> models);
}