package com.yuezhu.crawler.model;

import lombok.Data;

import java.util.Date;
@Data
public class CloudParkingSpace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.collect_flag
     *
     * @mbggenerated
     */
    private String collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.rent_sale_flag
     *
     * @mbggenerated
     */
    private String rentSaleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.publish_source
     *
     * @mbggenerated
     */
    private String publishSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.publish_time
     *
     * @mbggenerated
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.publish_man_name
     *
     * @mbggenerated
     */
    private String publishManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.publish_man_phone
     *
     * @mbggenerated
     */
    private String publishManPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_name
     *
     * @mbggenerated
     */
    private String parkingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.price_one
     *
     * @mbggenerated
     */
    private String priceOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.price_two
     *
     * @mbggenerated
     */
    private String priceTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_catagory
     *
     * @mbggenerated
     */
    private String parkingCatagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_acreage
     *
     * @mbggenerated
     */
    private String parkingAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.first_pay
     *
     * @mbggenerated
     */
    private String firstPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_type
     *
     * @mbggenerated
     */
    private String parkingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_address
     *
     * @mbggenerated
     */
    private String parkingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.parking_desc
     *
     * @mbggenerated
     */
    private String parkingDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.begin_rent_time
     *
     * @mbggenerated
     */
    private String beginRentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.pay_method
     *
     * @mbggenerated
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.remaining_rent_time
     *
     * @mbggenerated
     */
    private String remainingRentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.county_name
     *
     * @mbggenerated
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.county_code
     *
     * @mbggenerated
     */
    private String countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_parking_space.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
    private int pageSize;
    private  String synReal;
}