package com.yuezhu.crawler.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class CloudDataCollect {
    private Integer id;
    private String url;
    private String pics;
    private String name;
    private String price;
    private String house_type;
    private String area;
    private String unit_price;
    private String decorate;
    private String source;
    private String type;
    private String floor;
    private String flush_time;
    private String address;
    private String detail_url;
    private String concat;
    private String telephone;
    private String summary;
    private String search_area;
    private String search_resource;
    private String search_method;
    private String search_type;
    private String search_rent;
    private String search_price;
    private String search_special;
    private String search_subway;
    private String search_subway_distance;
    private String search_school_special;
    private String search_house_type;
    private String search_house_derection;
    private String search_near_subway;
    private String search_has_lift;
    private String search_decorate;
    private String search_has_pic;
    private String search_floor_cout;
    private String search_equity;
    private String search_house_age;
    private String backup1;
    private String backup2;
    private String backup3;
    private String backup4;
    private String backup5;
    private String belong_community;
    private String property_price;
    private String tax;
    private String tax_method;
    private String house_derection;
    private String ownership;
    private String house_age;
    private String search_area_size;
    private String search_class;
    private String rent_method;
    private String search_favorable;
    private String see_house_occasion;
    private String suit_stay;
    private String search_unit_price;
    private String shop_standard;
    private String shop_status;
    private String shop_pay_method;
    private String shop_manage_industry;
    private String shop_rent_begTime;
    private String shop_passenger_flow;
    private String shop_expect_profit;
    private String can_regit_company;
    private String use_rate;
    private String factory_oneFloor_high;
    private String factory_one_pay;
    private String land_plan_apply;
    private String park_type;
    private String telephone_two_diamension;
    private String bulid_name;
    private String property_company;
    private String support_facility;
    private String search_shop_industry;
    private String shop_face_width;
    private String shop_enter_depth;
    private String shop_layer_height;
    private String shop_can_split;
    private String font_base64;
}