package com.yuezhu.crawler.model;

import lombok.Data;

import java.util.Date;
@Data
public class CloudDataOffice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.collect_flag
     *
     * @mbggenerated
     */
    private String collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.collect_page
     *
     * @mbggenerated
     */
    private String collectPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.rent_sale_flag
     *
     * @mbggenerated
     */
    private String rentSaleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.catagory
     *
     * @mbggenerated
     */
    private String catagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.publish_source
     *
     * @mbggenerated
     */
    private String publishSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.rent_price_one
     *
     * @mbggenerated
     */
    private String rentPriceOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.rent_price_two
     *
     * @mbggenerated
     */
    private String rentPriceTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.is_split
     *
     * @mbggenerated
     */
    private String isSplit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.office_premises
     *
     * @mbggenerated
     */
    private String officePremises;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.publish_man_name
     *
     * @mbggenerated
     */
    private String publishManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.publish_man_phone
     *
     * @mbggenerated
     */
    private String publishManPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.location_floor
     *
     * @mbggenerated
     */
    private String locationFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.structure_acreage
     *
     * @mbggenerated
     */
    private String structureAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.decoration_situaion
     *
     * @mbggenerated
     */
    private String decorationSituaion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.can_register
     *
     * @mbggenerated
     */
    private String canRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.user_rate
     *
     * @mbggenerated
     */
    private String userRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.begin_rent_date
     *
     * @mbggenerated
     */
    private String beginRentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.pay_method
     *
     * @mbggenerated
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.property_fee
     *
     * @mbggenerated
     */
    private String propertyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.refer_station_num
     *
     * @mbggenerated
     */
    private String referStationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.matchings
     *
     * @mbggenerated
     */
    private String matchings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.sale_price_one
     *
     * @mbggenerated
     */
    private String salePriceOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.sale_price_two
     *
     * @mbggenerated
     */
    private String salePriceTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_data_office.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
    private String countyCode;
    private String countyName;
    private String cityCode;
    private String cityName;
    private String provinceCode;
    private String provinceName;
    private String synReal;
    private int pageSize;
}