package com.yuezhu.crawler.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class CloudNewPremises {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.url_unique
     *
     * @mbggenerated
     */
    private String urlUnique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.url_detail
     *
     * @mbggenerated
     */
    private String urlDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.url_pic
     *
     * @mbggenerated
     */
    private String urlPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.url_house_type
     *
     * @mbggenerated
     */
    private String urlHouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.collect_flag_one
     *
     * @mbggenerated
     */
    private String collectFlagOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.collect_flag_two
     *
     * @mbggenerated
     */
    private String collectFlagTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.collect_flag_three
     *
     * @mbggenerated
     */
    private String collectFlagThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_name
     *
     * @mbggenerated
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_alias
     *
     * @mbggenerated
     */
    private String communityAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_desc
     *
     * @mbggenerated
     */
    private String communityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.business_district
     *
     * @mbggenerated
     */
    private String businessDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_addrdss
     *
     * @mbggenerated
     */
    private String communityAddrdss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_catagory
     *
     * @mbggenerated
     */
    private String propertyCatagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.developer
     *
     * @mbggenerated
     */
    private String developer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.completion_time
     *
     * @mbggenerated
     */
    private String completionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.structure_category
     *
     * @mbggenerated
     */
    private String structureCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.volume_rate
     *
     * @mbggenerated
     */
    private String volumeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.greening_rate
     *
     * @mbggenerated
     */
    private String greeningRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_costs
     *
     * @mbggenerated
     */
    private String propertyCosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_costs_unit
     *
     * @mbggenerated
     */
    private String propertyCostsUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_company
     *
     * @mbggenerated
     */
    private String propertyCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_manage_attach
     *
     * @mbggenerated
     */
    private String propertyManageAttach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.floor_area
     *
     * @mbggenerated
     */
    private String floorArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.structure_area
     *
     * @mbggenerated
     */
    private String structureArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.total_household
     *
     * @mbggenerated
     */
    private String totalHousehold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.cur_period_household
     *
     * @mbggenerated
     */
    private String curPeriodHousehold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.parking_rent
     *
     * @mbggenerated
     */
    private String parkingRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.parking_sale
     *
     * @mbggenerated
     */
    private String parkingSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.parking_desc
     *
     * @mbggenerated
     */
    private String parkingDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.equity_des
     *
     * @mbggenerated
     */
    private String equityDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_office_phone
     *
     * @mbggenerated
     */
    private String propertyOfficePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_office_address
     *
     * @mbggenerated
     */
    private String propertyOfficeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_door
     *
     * @mbggenerated
     */
    private String communityDoor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.structure_frame
     *
     * @mbggenerated
     */
    private String structureFrame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.provide_water
     *
     * @mbggenerated
     */
    private String provideWater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.provide_elect
     *
     * @mbggenerated
     */
    private String provideElect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.provide_heating
     *
     * @mbggenerated
     */
    private String provideHeating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.provede_gas
     *
     * @mbggenerated
     */
    private String provedeGas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.communication_facility
     *
     * @mbggenerated
     */
    private String communicationFacility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.elevator_service
     *
     * @mbggenerated
     */
    private String elevatorService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.security_manage
     *
     * @mbggenerated
     */
    private String securityManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.health_service
     *
     * @mbggenerated
     */
    private String healthService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.traffic_situation
     *
     * @mbggenerated
     */
    private String trafficSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.univercity
     *
     * @mbggenerated
     */
    private String univercity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.middle_primary_school
     *
     * @mbggenerated
     */
    private String middlePrimarySchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.nursery_school
     *
     * @mbggenerated
     */
    private String nurserySchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.shop_market
     *
     * @mbggenerated
     */
    private String shopMarket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.post_office
     *
     * @mbggenerated
     */
    private String postOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.bank
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.other_matching
     *
     * @mbggenerated
     */
    private String otherMatching;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.opening_ceremony_time
     *
     * @mbggenerated
     */
    private String openingCeremonyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.deliver_house_time
     *
     * @mbggenerated
     */
    private String deliverHouseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.open_ceremony_flag
     *
     * @mbggenerated
     */
    private String openCeremonyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.special_room
     *
     * @mbggenerated
     */
    private Byte specialRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.premises_avg_price
     *
     * @mbggenerated
     */
    private String premisesAvgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.project_special
     *
     * @mbggenerated
     */
    private String projectSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.property_desc
     *
     * @mbggenerated
     */
    private String propertyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.upload_video
     *
     * @mbggenerated
     */
    private String uploadVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.decoration_situation
     *
     * @mbggenerated
     */
    private String decorationSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.loop_position
     *
     * @mbggenerated
     */
    private String loopPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.premises_favorable
     *
     * @mbggenerated
     */
    private String premisesFavorable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.sale_premises_address
     *
     * @mbggenerated
     */
    private String salePremisesAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.support_hotline
     *
     * @mbggenerated
     */
    private String supportHotline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.main_unit
     *
     * @mbggenerated
     */
    private String mainUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.community_inner_matching
     *
     * @mbggenerated
     */
    private String communityInnerMatching;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.premises_total
     *
     * @mbggenerated
     */
    private String premisesTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.floor_condition
     *
     * @mbggenerated
     */
    private String floorCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_new_premises.backup3
     *
     * @mbggenerated
     */
    private String backup3;
    private String collectFlagEffect;
    private String cityName;
    private String districtName;
    private String synReal;

    //扩展字段
    private int pageSize;
    private Integer switchFlag;//自定义开关 1-户型url不为null
}