package com.yuezhu.crawler.model;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
@Data
public class CloudHouseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.refer_id
     *
     * @mbggenerated
     */
    private String referId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.bedroom_num
     *
     * @mbggenerated
     */
    private String bedroomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.livingroom_num
     *
     * @mbggenerated
     */
    private String livingroomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.bathroom_num
     *
     * @mbggenerated
     */
    private String bathroomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.kitchen_num
     *
     * @mbggenerated
     */
    private String kitchenNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.structure_acreage
     *
     * @mbggenerated
     */
    private String structureAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.sale_situation
     *
     * @mbggenerated
     */
    private String saleSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.refer_avg_price
     *
     * @mbggenerated
     */
    private BigDecimal referAvgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.refer_total_price
     *
     * @mbggenerated
     */
    private BigDecimal referTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.house_type_distribute
     *
     * @mbggenerated
     */
    private String houseTypeDistribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.house_type_analysis
     *
     * @mbggenerated
     */
    private String houseTypeAnalysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.house_type_img
     *
     * @mbggenerated
     */
    private String houseTypeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_house_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_house_type.id
     *
     * @return the value of cloud_house_type.id
     *
     * @mbggenerated
     */
}