package com.yuezhu.crawler.model;

import lombok.Data;
import java.util.Date;
@Data
public class CloudSecondHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.collect_flag
     *
     * @mbggenerated
     */
    private String collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.collect_page
     *
     * @mbggenerated
     */
    private String collectPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.community_name
     *
     * @mbggenerated
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.area_location
     *
     * @mbggenerated
     */
    private String areaLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.see_house_time
     *
     * @mbggenerated
     */
    private String seeHouseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.publish_man_name
     *
     * @mbggenerated
     */
    private String publishManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.publish_man_phone
     *
     * @mbggenerated
     */
    private String publishManPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.publish_man_type
     *
     * @mbggenerated
     */
    private String publishManType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_type
     *
     * @mbggenerated
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.floor_location
     *
     * @mbggenerated
     */
    private String floorLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.structure_acreage
     *
     * @mbggenerated
     */
    private String structureAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_construction
     *
     * @mbggenerated
     */
    private String houseConstruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.structure_type
     *
     * @mbggenerated
     */
    private String structureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_orient
     *
     * @mbggenerated
     */
    private String houseOrient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.build_construction
     *
     * @mbggenerated
     */
    private String buildConstruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.decoration_condition
     *
     * @mbggenerated
     */
    private String decorationCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.terrace_rate
     *
     * @mbggenerated
     */
    private String terraceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.has_elevator
     *
     * @mbggenerated
     */
    private String hasElevator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.property_age
     *
     * @mbggenerated
     */
    private String propertyAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.list_time
     *
     * @mbggenerated
     */
    private String listTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.trade_right
     *
     * @mbggenerated
     */
    private String tradeRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.last_trade
     *
     * @mbggenerated
     */
    private String lastTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_using
     *
     * @mbggenerated
     */
    private String houseUsing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_age
     *
     * @mbggenerated
     */
    private String houseAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.property_owning
     *
     * @mbggenerated
     */
    private String propertyOwning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.mortgage
     *
     * @mbggenerated
     */
    private String mortgage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.room_book_record
     *
     * @mbggenerated
     */
    private String roomBookRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.house_characters
     *
     * @mbggenerated
     */
    private String houseCharacters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.sale_feature
     *
     * @mbggenerated
     */
    private String saleFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.community_introduce
     *
     * @mbggenerated
     */
    private String communityIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.surrond_matchings
     *
     * @mbggenerated
     */
    private String surrondMatchings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.traffic_travel
     *
     * @mbggenerated
     */
    private String trafficTravel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_second_house.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
    private int pageSize;
    private String premisesCity;
    private String premisesDistrict;
    private String synReal;
}