package com.yuezhu.crawler.model;
import lombok.Data;
import java.util.Date;
@Data
public class CloudRentHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.collect_flag
     *
     * @mbggenerated
     */
    private String collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.collect_page
     *
     * @mbggenerated
     */
    private String collectPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.whole_part
     *
     * @mbggenerated
     */
    private String wholePart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.labels
     *
     * @mbggenerated
     */
    private String labels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.rent_price_one
     *
     * @mbggenerated
     */
    private String rentPriceOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.rent_price_two
     *
     * @mbggenerated
     */
    private String rentPriceTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.house_catagory
     *
     * @mbggenerated
     */
    private String houseCatagory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.rent_time_method
     *
     * @mbggenerated
     */
    private String rentTimeMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.decoration_situation
     *
     * @mbggenerated
     */
    private String decorationSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.pay_method
     *
     * @mbggenerated
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.see_house_time
     *
     * @mbggenerated
     */
    private String seeHouseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.house_type
     *
     * @mbggenerated
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.house_acreage
     *
     * @mbggenerated
     */
    private String houseAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.house_orient
     *
     * @mbggenerated
     */
    private String houseOrient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.publish_man_name
     *
     * @mbggenerated
     */
    private String publishManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.publish_man_phone
     *
     * @mbggenerated
     */
    private String publishManPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.publish_time
     *
     * @mbggenerated
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.enter_rent_time
     *
     * @mbggenerated
     */
    private String enterRentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.rent_time
     *
     * @mbggenerated
     */
    private String rentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.floor_location
     *
     * @mbggenerated
     */
    private String floorLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.elevator
     *
     * @mbggenerated
     */
    private String elevator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.parking_space
     *
     * @mbggenerated
     */
    private String parkingSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.use_water
     *
     * @mbggenerated
     */
    private String useWater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.use_power
     *
     * @mbggenerated
     */
    private String usePower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.use_gas
     *
     * @mbggenerated
     */
    private String useGas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.matchings
     *
     * @mbggenerated
     */
    private String matchings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_rent_house.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
    private String countyCode;
    private String countyName;
    private String cityCode;
    private String cityName;
    private String provinceCode;
    private String provinceName;
    private String synReal;
    //扩展属性
    private int pageSize;
}