package com.yuezhu.crawler.model;
import lombok.Data;
import java.util.Date;
@Data
public class CloudPioneerPark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.collect_flag
     *
     * @mbggenerated
     */
    private String collectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.rent_sale_flag
     *
     * @mbggenerated
     */
    private String rentSaleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.publish_source
     *
     * @mbggenerated
     */
    private String publishSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.publish_time
     *
     * @mbggenerated
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.publish_man_name
     *
     * @mbggenerated
     */
    private String publishManName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.publish_man_phone
     *
     * @mbggenerated
     */
    private String publishManPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.pioneer_name
     *
     * @mbggenerated
     */
    private String pioneerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.price_one
     *
     * @mbggenerated
     */
    private String priceOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.price_two
     *
     * @mbggenerated
     */
    private String priceTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.structure_acreage
     *
     * @mbggenerated
     */
    private String structureAcreage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.contain_work_num
     *
     * @mbggenerated
     */
    private String containWorkNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.decorate_situation
     *
     * @mbggenerated
     */
    private String decorateSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.can_register
     *
     * @mbggenerated
     */
    private String canRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.free_time
     *
     * @mbggenerated
     */
    private String freeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.earliest_rent
     *
     * @mbggenerated
     */
    private String earliestRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.shortest_rent
     *
     * @mbggenerated
     */
    private String shortestRent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.price_adventage
     *
     * @mbggenerated
     */
    private String priceAdventage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.see_house
     *
     * @mbggenerated
     */
    private String seeHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.decorate_infos
     *
     * @mbggenerated
     */
    private String decorateInfos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.acreage_infos
     *
     * @mbggenerated
     */
    private String acreageInfos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.house_characteristic
     *
     * @mbggenerated
     */
    private String houseCharacteristic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.pics
     *
     * @mbggenerated
     */
    private String pics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premises_id
     *
     * @mbggenerated
     */
    private String premisesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premises_name
     *
     * @mbggenerated
     */
    private String premisesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premises_price
     *
     * @mbggenerated
     */
    private String premisesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premises_address
     *
     * @mbggenerated
     */
    private String premisesAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premise_subway
     *
     * @mbggenerated
     */
    private String premiseSubway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premise_popularities
     *
     * @mbggenerated
     */
    private String premisePopularities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.premise_renting
     *
     * @mbggenerated
     */
    private String premiseRenting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.surrond_matchings
     *
     * @mbggenerated
     */
    private String surrondMatchings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.syn_real
     *
     * @mbggenerated
     */
    private String synReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.backup1
     *
     * @mbggenerated
     */
    private String backup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.backup2
     *
     * @mbggenerated
     */
    private String backup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.backup3
     *
     * @mbggenerated
     */
    private String backup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_pioneer_park.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

   private Integer pageSize;
   private String cityName;

}