package com.yuezhu.crawler.model;

import lombok.Data;

import java.util.Date;
@Data
public class CloudProfessionFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.refer_id
     *
     * @mbggenerated
     */
    private String referId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.one_class
     *
     * @mbggenerated
     */
    private Byte oneClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.second_class
     *
     * @mbggenerated
     */
    private Byte secondClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.file_url
     *
     * @mbggenerated
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_profession_file.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
}